ClothingBazaar.web/ViewModels/ProductViewModel.cs
using ClothingBazaar.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ClothingBazaar.web.ViewModels
{
    public class ProductSearchViewModel
    {
        public List<Product> Products { get; set; }
        public string SearchTerm { get; set; }
    }

    public class NewProductViewModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public DateTime AddedOn { get; set; }
        public string ImageUrl { get; set; }

        public List<Category> categories { get; set; }
    }

    public class EditProductViewModel
    {
        public int ID { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public DateTime AddedOn { get; set; }
        public string ImageUrl { get; set; }

        public List<Category> AvailableCategories { get; set; }
    }
}

ClothingBazaar.web/Controllers/ProductController.cs
using ClothingBazaar.Entities;
using ClothingBazaar.Services;
using ClothingBazaar.web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothingBazaar.web.Controllers
{
    public class ProductController : Controller
    {
        //ProductsService productsService = new ProductsService(); //using Singleton so disabling this.
        //CategoriesService categoriesService = new CategoriesService();

        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductTable(string search)
        {
            ProductSearchViewModel model = new ProductSearchViewModel();
            model.Products = ProductsService.Instance.GetProducts();

            if (string.IsNullOrEmpty(search) == false)
            {
                model.SearchTerm = search;
                model.Products = model.Products.Where(p => p.Name != null && p.Name.ToLower().Contains(search.ToLower())).ToList();
            }

            return PartialView(model);
        }

        #region Creation

        public ActionResult Create()
        {
            NewProductViewModel model = new NewProductViewModel();

            model.categories = CategoriesService.Instance.GetAllCategories();
            return PartialView(model);
        }
        
        [HttpPost]
        public ActionResult Create(NewProductViewModel model)
        {

            var newProduct = new Product();
            newProduct.Name = model.Name;
            newProduct.Price = model.Price;
            newProduct.Description = model.Description;
            newProduct.Category = CategoriesService.Instance.GetCategory(model.CategoryID); 
            newProduct.ImageUrl = model.ImageUrl;
            newProduct.AddedOn = model.AddedOn;
            

            ProductsService.Instance.SaveProduct(newProduct); 

            return RedirectToAction("ProductTable");
        }
        #endregion

        #region Modification
        public ActionResult Edit(int ID)
        {
            EditProductViewModel model = new EditProductViewModel();

            var product = ProductsService.Instance.GetProduct(ID);

            model.ID = product.ID;
            model.Name = product.Name;
            model.Description = product.Description;
            model.Price = product.Price;
            model.CategoryID = product.Category != null ? product.Category.ID : 0;
            model.ImageUrl = product.ImageUrl;
            model.AddedOn = product.AddedOn;
            model.AvailableCategories = CategoriesService.Instance.GetAllCategories();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(EditProductViewModel model)
        {
            var existingProduct = ProductsService.Instance.GetProduct(model.ID);
            existingProduct.Name = model.Name;
            existingProduct.Description = model.Description;
            existingProduct.Price = model.Price;
            existingProduct.ImageUrl = model.ImageUrl;
            existingProduct.Category = CategoriesService.Instance.GetCategory(model.CategoryID);
            //existingProduct.CategoryID = model.CategoryID;

            ProductsService.Instance.UpdateProduct(existingProduct);

            return RedirectToAction("ProductTable");
            
        }
        #endregion

        #region Delete
        [HttpPost]
        public ActionResult Delete(int ID)
        {
            ProductsService.Instance.DeleteProduct(ID);

            return RedirectToAction("ProductTable");
        }
        #endregion
    }
}

ClothingBazaar.web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothingBazaar.web.Controllers
{
    public class SharedController : Controller
    {

        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult(); //Accessing JSON
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0]; //Catching the request received from the server along with the file that was uploaded
                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName); //Creates random alphanumeric string for the name of the file.
                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);

                file.SaveAs(path);

                result.Data = new { success = true, ImageUrl = string.Format("/content/images/{0}", fileName) }; 
            }
            catch (Exception ex)
            {
                result.Data = new { success = false, Message = ex.Message };
            }

            return result;
        }
    }
}

ClothingBazaar.web/Views/Product/Create.cshtml
<!--//Since we have referenced 'ClothingBazar.Web' in web.config, we will not have to use the full reference again. we can only pass the model deirectly.-->
@model NewProductViewModel
@{
    ViewBag.Title = "Create";

    var date = DateTime.Now;
}

<h2>Create Product</h2>

<form id="createProduct">
    <div class="form-group">
        <label>Category</label>
        <select class="form-control" name="CategoryID">
            @foreach (var category in Model.categories)
            {
                <option value="@category.ID">@category.Name</option>
            }
        </select>
    </div>
    <input type="hidden" class="form-control" name="AddedOn" value="@date" />
    <div class="form-group">
        <label>Name</label>
        <input class="form-control" name="Name" />
    </div>
    <div class="form-group">
        <label>Description</label>
        <input class="form-control" name="Description" />
    </div>
    <div class="form-group">
        <label>Price</label>
        <input class="form-control" name="Price" />
    </div>
    <div class="form-group">
        <label>Image</label>
        <input id="productImageURL" name="ImageURL" type="hidden" />
        <input class="form-control" id="productImageUpload" name="Image" type="file" />
    </div>
    <img id="productImageContainer" />
    <button id="saveBtn" type="button" class="btn btn-primary">Save</button>
    <button id="cancelBtn" type="button" class="btn btn-primary">Cancel</button>
</form>

<!--#region Old Code-->
@*<form id="createForm">
        <div class="form-group">
            <label>Category</label>
            <select name="CategoryID" class="form-control">
                <option disabled selected> -- Select a category -- </option> <!--Default selection of dropdown-->
                @foreach (var category in Model)
                {
                    <option value="@category.ID">@category.Name</option>//We will pass the 'value' of the category ID.
                }

            </select>
        </div>

        <br />

        <input type="hidden" class="form-control" name="AddedOn" value="@date" />

        <div class="form-group">
            <label>Name</label>
            <input class="form-control" name="Name" />
        </div>
        <br />

        <div class="form-group">
            <label>Description</label>
            <input class="form-control" name="Description" />
        </div>
        <br />

        <div class="form-group">
            <label>Price</label>
            <input class="form-control" name="Price" />
        </div>
        <div class="form-group">
            <label>Image</label>
            <input id="productImageURL" name="ImageURL" type="hidden" />
            <input class="form-control" id="productImageUpload" name="Image" type="file" />
        </div>
        <br />

        <img id="productImageContainer" />

        <br />

        <button type="button" class="btn btn-primary" id="saveBtn">Save</button>
    </form>*@
<!--#endregion Old Code-->

<script>
    $("#saveBtn").click(function () {
        $.ajax({
            type: "POST",
            url: '@Url.Action("Create", "Product")', //'/Product/Create',
            data: $("#createProduct").serialize() //Picks all the values in the text boxes.
        })
            .done(function (response) {
                focusAction("tableContainer");
                $("#tableContainer").html(response);
                $("#createContainer").html("");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#cancelBtn").click(function () {
        focusAction("tableContainer");
        $("#createContainer").html("");
    });

    $("#productImageUpload").change(function () {

        //so basically .serialize function also creates an object of form data and sends it.
        //Here, we are not using any kind of form or .serialize but we have to send the image data therefore, we have to create
        //an object of form data initially.
        var formData = new FormData();

        var element = this;
        var totalfiles = element.files.length;

        for (var i = 0; i < totalfiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")', //'/Shared/UploadImage',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
            .done(function (response) {

                if (response.success) {
                    $("#productImageURL").val(response.ImageUrl);
                    $("#productImageContainer").attr("src", response.ImageUrl);
                }
                console.log(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            })
    })
</script>

ClothingBazaar.web/Views/Product/Edit.cshtml
@model EditProductViewModel

@{
    ViewBag.Title = "Edit";

    var plaeceholder = "";

    if (Model.ImageUrl != "")
    {
        plaeceholder = Model.ImageUrl;
    }
    else
    {
        plaeceholder = "";
    }

}

<h2>Edit Product</h2>

<form id="editProduct">
    <input type="hidden" name="ID" value="@Model.ID" />

    <div class="form-group">
        <label>Category</label>
        <select class="form-control" name="CategoryID">
            @foreach (var category in Model.AvailableCategories)
            {
                var selected = category.ID == Model.CategoryID ? "selected" : string.Empty;
                <option value="@category.ID" @selected>@category.Name</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label>Name</label>
        <input class="form-control" name="Name" value="@Model.Name" />
    </div>
    <div class="form-group">
        <label>Description</label>
        <input class="form-control" name="Description" value="@Model.Description" />
    </div>
    <div class="form-group">
        <label>Price</label>
        <input class="form-control" name="Price" value="@Model.Price" />
    </div>

    <div class="form-group">
        <label>Edit Image</label>
        <input id="productEditImageURL" name="ImageURL" type="hidden" value="@plaeceholder" />
        <input id="productEditImageUpload" class="form-control" name="Image" type="file" />
    </div>
    <label>Current Image Selected</label>
    <br />
    <div id="ImageProductCaption"></div>

    <img id="EditProductImageContainer" src=@plaeceholder>

    <br />

    <br />
    <img id="productEditImageContainer">

    <br />

    <button id="updateBtn" type="button" class="btn btn-primary">Update</button>
    <button id="cancelBtn" type="button" class="btn btn-primary">Cancel</button>
</form>

<!--#region Old Code-->
@*<form id="editForm">
    <div class="form-group">

        <div class="form-group">
            <label>Category</label>
            <select name="CategoryID" class="form-control">
                @{
                    var modelcatname = "";
                    if (Model.Products.Category != null)
                    {
                        modelcatname = Model.Products.Category.Name;
                    }
                    else
                    {
                        modelcatname = "-- Select a Category --";
                    }
                }
                @*<option disabled selected> @modelcatname </option> @*Default selection of dropdown*@
                @*@foreach (var category in Model.Categories)
                {
                    <option value="@category.ID">@category.Name</option>//We will pass the 'value' of the category ID.
                }*@

            @*</select>
        </div>*@


        @*<input type="hidden" name="ID" value="@Model.Products.ID" />
        <div class="form-group">
            @*To submit a button, set it up in a form tag*@
            @*<label>Name</label>
            <input class="form-control" name="Name" value="@Model.Products.Name" />*@
        @*</div>

        <br /> @*Adds a line in between Name and Description*@

        @*<div class="form-group">
            @*To submit a button, set it up in a form tag*@
            @*<label>Description</label>
            <input class="form-control" name="Description" value="@Model.Products.Description" />
        </div>*@

        @*<br />*@

        @*<div class="form-group">
            @*To submit a button, set it up in a form tag*@
            @*<label>Price</label>
            <input class="form-control" name="Price" value="@Model.Products.Price" />*@
        @*</div>

        <br />*@

        @*<div class="form-group">
            <label>Edit Image</label>
            <input id="productEditImageURL" name="ImageURL" type="hidden" />
            <input id="productEditImageUpload" class="form-control" name="Image" type="file" />
        </div>*@

        @*<br />
        <img id="productEditImageContainer">

        <br />

        <button type="button" class="btn btn-primary" id="updateBtn">Update</button>
    </div>
</form>*@
<!--#endregion-->

<script>
    $(document).ready(function () {
        debugger;
        if ('@Model.ImageUrl' != '') {
            $("#EditProductImageContainer").attr("src", '@Model.ImageUrl');
        }
        else {
            $("#ImageProductCaption").append("<p>No image assigned to this Category.</p>");
        }
    });

    $("#cancelBtn").click(function () {
        focusAction("tableContainer");
        $("#createContainer").html("");
    });

    $("#updateBtn").click(function () {

        $.ajax({
            type: "POST",
            url: '@Url.Action("Edit", "Product")', //'/Product/Edit',
            data: $("#editProduct").serialize() //Picks all the values in the text boxes.
        })
            .done(function (response) {
                focusAction("tableContainer");
                $("#tableContainer").html(response);
                $("#createContainer").html("");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#productEditImageUpload").change(function () {
        var formData = new FormData();

        var element = this;
        var totalfiles = element.files.length;

        for (var i = 0; i < totalfiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")', //'/Shared/UploadImage',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
            .done(function (response) {

                if (response.success) {
                    $("#productEditImageURL").val(response.ImageUrl);
                    //This 'ImageUrl' should have the same name as in Shared Controller
                    $("#productEditImageContainer").attr("src", response.ImageUrl);
                    $("#ImageCategoryCaption").remove();
                }
                console.log(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            })
    })
</script>

ClothingBazaar.web/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section">
                    <h2 class="title">
                        Products
                    </h2>
                </div>
            </div>
        </div>

        <div id="tableContainer">
            @{
                Html.RenderAction("ProductTable");
            }
        </div>

        <hr />

        <div id="createContainer">

        </div>
    </div>
</section>

<script>
       function focusAction(controlToFocus) {
        $('html, body').animate({
            scrollTop: $("#" + controlToFocus).offset().top - 100
        }, 1000);
    }
</script>

ClothingBazaar.web/Views/Product/ProductTable.cshtml
@model ClothingBazaar.web.ViewModels.ProductSearchViewModel

@{
    /**/

    ViewBag.Title = "ProductTable";
}

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
<script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

<style>
    input.form-control::placeholder {
        opacity: 0.5;
    }
</style>

<div>
    <form method="post">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Search</label>
                    <input class="form-control" id="searchTxt" name="Search" value="@Model.SearchTerm" placeholder="Search" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Action</label>
                    <div class="row">
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="searchBtn">Search</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="resetBtn">Reset</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="newBtn">New</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<!--#region Old Code  -->
@*<div>
        <form method="post">
            <div class="row">
                <div class="col-md-8">
                    <input class="form-control" name="Search" id="searchTxt" placeholder="Search" />
                </div>
                <div class="col-md-4">
                    <button type="button" id="searchBtn">Search</button>
                    <button type="button" id="newBtn">New</button>
                </div>
            </div>
        </form>
    </div>*@

@*<div>
    <table class="table table-striped">
        <thead class="thead-default">
            <tr>
                <td scope="col">Product Name</td>
                <td scope="col">Category</td>
                <td>Price</td>
                <td>Actions</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var products in Model)
            {
                <tr>
                    <td>@products.Name</td>
                    <td>
                        @if (products.Category != null)
                        {
                            <text>@products.Category.Name</text>
                        }
                        else
                        {
                            <text>-</text>
                        }
                    </td>
                    <td>@products.Price</td>
                    <td>
                        <button class="editBtn" data-id="@products.ID">Edit</button>
                        <button class="deleteBtn" data-id="@products.ID">Delete</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>*@

<!--#endregion -->

<div class="container" style="text-align-last: center">
    <table id="productsTable" class="table table-striped">
        <thead style="font-weight: bold">
            <tr>
                <th>Product Name</th>
                <th>Category</th>
                <th>Price</th>
                <th class="wrap-td">Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Products != null && Model.Products.Count > 0)
            {

                foreach (var product in Model.Products)
                {
                    <tr>
                        <td>@product.Name</td>
                        <td>
                            @if (product.Category != null)
                            {
                                <text>@product.Category.Name</text>
                            }
                            else
                            {
                                <text>-</text>
                            }
                        </td>
                        <td>@product.Price</td>
                        <td class="wrap-td">
                            <button class="editBtn" data-id="@product.ID">Edit</button>
                            <button class="deleteBtn" data-id="@product.ID">Delete</button>
                            <button class="addToCart" data-id="@product.ID">Add To Cart</button>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td class="text-danger" colspan="4">No Products found.</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    $('#productsTable').DataTable(); //Used for Pagination (Datatables)

    $(".deleteBtn").click(function () {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Delete", "Product")', //'/Product/Delete',
            data: {
                ID: $(this).attr('data-id')
            }
        })
            .done(function (response) {
                focusAction("tableContainer");
                $("#tableContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $(".editBtn").click(function () {
        focusAction("createContainer");
        $.ajax({
            url: '@Url.Action("Edit", "Product")', //'/Product/Edit',
            data: {
                ID: $(this).attr('data-id')
            }
        })
            .done(function (response) {
                $("#createContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#newBtn").click(function () {
        focusAction("createContainer");
        $.ajax({
            url: '@Url.Action("Create", "Product")', //'/Product/Create',
        })
            .done(function (response) {
                $("#createContainer").html(response);
                focusAction();
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#searchBtn").click(function () {

        var searchValue = $("#searchTxt").val();

        $.ajax({
            url: '@Url.Action("ProductTable", "Product")', //'/Product/ProductTable',
            data: {
                search: searchValue
            }
        })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#resetBtn").click(function () {
        focusAction("tableContainer");
        var searchValue = "";

        $.ajax({
            url: '@Url.Action("ProductTable", "Product")', //'/Product/ProductTable',
            data: {
                search: searchValue
            }
        })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    var products = [];

    $(".addToCart").click(function () {
        var productID = $(this).attr('data-id') //GETTING THE ID OF THE PRODUCT

        products.push(productID);

        $.cookie('CartProducts', products.join('-'), { path: '/' }); //Assigning the product id that the cx wants to buy -- products.join() gives you an option to join all the number together
        //putting the path parameter in here for the cookie to be accessible all over the website.

        alert("Added to cart");
    });
</script>