ClothingBazaar.web/ViewModels/CategoryViewModel.cs
using ClothingBazaar.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ClothingBazaar.web.ViewModels
{
    public class CategorySearchViewModel
    {
        public List<Category> Categories { get; set; }
        public string SearchTerm { get; set; }
        public Pager Pager { get; set; }
    }

    public class NewCategoryViewModel
    {
        [Required]
        [MinLength(3), MaxLength(50)]
        public string Name { get; set; }

        [MaxLength(500)]
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public bool isFeatured { get; set; }
    }

    public class EditCategoryViewModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public bool isFeatured { get; set; }
    }

    
}

ClothingBazaar.web/Controllers/CategoryController.cs
using ClothingBazaar.Entities;
using ClothingBazaar.web.ViewModels;
using ClothingBazaar.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace ClothingBazaar.web.Controllers
{
    public class CategoryController : Controller 
    {
        //CategoriesService categoryService = new CategoriesService(); //Creating an object of the serivce.

        public ActionResult CategoryTable(String search, int? pageNo)
        {
            CategorySearchViewModel model = new CategorySearchViewModel();

            model.SearchTerm = search;
            int pageSize = 5; //int.Parse(ConfigurationService.Instance.GetConfig("ListingPageSize").Value);

            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;

            var totalRecords = CategoriesService.Instance.GetCategoriesCount(search);
            model.Categories = CategoriesService.Instance.GetCategories(search, pageNo.Value);

            if(model.Categories != null)
            {
                model.Pager = new Pager(totalRecords, pageNo, pageSize);

                return PartialView(model);
            }
            else
            {
                return HttpNotFound();
            }
            
        }

        public ActionResult Index()
        {
            return View();
        }

        // GET: Category
        public ActionResult Create()
        {
            NewCategoryViewModel model = new NewCategoryViewModel();

            return PartialView(model);
        }

        //POST: Category
        [HttpPost]
        public ActionResult Create(NewCategoryViewModel model) 
        {
            if (ModelState.IsValid)
            {
                var newCategory = new Category();
                newCategory.Name = model.Name;
                newCategory.Description = model.Description;
                newCategory.ImageURL = model.ImageURL;
                newCategory.isFeatured = model.isFeatured;

                CategoriesService.Instance.SaveCategory(newCategory); 

                return RedirectToAction("CategoryTable");
            }
            else
            {
                return new HttpStatusCodeResult(500);
            }
            
        }

        // GET: Edit
        public ActionResult Edit(int id)
        {
            EditCategoryViewModel model = new EditCategoryViewModel();

            var category = CategoriesService.Instance.GetCategory(id);
            model.ID = category.ID;
            model.Name = category.Name;
            model.Description = category.Description;
            model.ImageURL = category.ImageURL;
            model.isFeatured = category.isFeatured;

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(EditCategoryViewModel model)
        {
            var existingCategory = CategoriesService.Instance.GetCategory(model.ID);
            existingCategory.Name = model.Name;
            existingCategory.Description = model.Description;
            existingCategory.ImageURL = model.ImageURL;
            existingCategory.isFeatured = model.isFeatured;

            CategoriesService.Instance.UpdateCategory(existingCategory);

            return RedirectToAction("CategoryTable");
        }

        public ActionResult Delete(int id)
        {
            var category = CategoriesService.Instance.GetCategory(id);

            return PartialView(category);
        }

        [HttpPost]
        public ActionResult Delete(Category category)
        {
            CategoriesService.Instance.DeleteCategory(category.ID);

            return RedirectToAction("CategoryTable");
        }
    }
}

ClothingBazaar.web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothingBazaar.web.Controllers
{
    public class SharedController : Controller
    {

        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult(); //Accessing JSON
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0]; //Catching the request received from the server along with the file that was uploaded
                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName); //Creates random alphanumeric string for the name of the file.
                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);

                file.SaveAs(path);

                result.Data = new { success = true, ImageUrl = string.Format("/content/images/{0}", fileName) }; 
            }
            catch (Exception ex)
            {
                result.Data = new { success = false, Message = ex.Message };
            }

            return result;
        }
    }
}

ClothingBazaar.web/Views/Category/CategoryTable.cshtml
@model ClothingBazaar.web.ViewModels.CategorySearchViewModel


@{
    ViewBag.Title = "Index";
}

<style>
    input.form-control::placeholder {
        opacity: 0.5;
    }
</style>
<br />

<div>
    <form method="post">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Search</label>
                    <input class="form-control" id="searchTxt" name="Search" value="@Model.SearchTerm" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Action</label>
                    <div class="row">
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="searchBtn">Search</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="resetCatBtn">Reset</button>
                        </div>
                        <div class="col-md-4 pr-0">
                            <button class="btn btn-primary form-control" type="button" id="newCatBtn">New</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div>
    <table class="table table-striped">
        <thead>
            <tr>
                <td class="font-weight-bold">Category Name</td>
                <td class="font-weight-bold">Products</td>
                <td class="wrap-td font-weight-bold">Actions</td>
            </tr>
        </thead>
        <tbody>
            @if (Model.Categories != null && Model.Categories.Count > 0)
            {
                foreach (var category in Model.Categories)
                {
                    <tr>
                        <td>@category.Name</td>

                        <td>@category.Products.Count</td>
                        @*To include the count of products, the issue we were facing was the number of products were
                            not being added into the category itself. For this we had to make changes in
                            Category.Services when we fetch the categories. There we used the 'INLCUDE' method to include
                            all the products related to that category when fetching the data.*@
                        <td class="wrap-td">
                            <button class="editCatBtn" data-id="@category.ID">Edit</button>
                            <button class="deleteCatBtn" data-id="@category.ID">Delete</button>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr><td colspan="3" class="text-danger">No Categories found.</td></tr>
            }
        </tbody>
    </table>

    <div>
        @if (Model.Pager != null)
        {
            if (Model.Pager.CurrentPage > 1)
            {
                <button class="pageButtons" data-pageNo="1">First</button>
                <button class="pageButtons" data-pageNo="@(Model.Pager.CurrentPage - 1)">Previous</button>
            }

            for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
            {
                string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;
                <button class="@activeClass pageButtons" data-pageNo="@page">@page</button>
            }

            if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {
                <button class="pageButtons" data-pageNo="@(Model.Pager.CurrentPage + 1)">Next</button>
                <button class="pageButtons" data-pageNo="@(Model.Pager.EndPage)">Last</button>
            }
        }
    </div>

</div>

<!--#region Old Code  -->
@*<div class="row">
        <div class="col-md-12">
            <div class="title-section">
                <h2 class="title">
                    Category Table
                </h2>
            </div><!-- /.title-section -->
        </div><!-- /.col-md-12 -->
    </div>*@

@*<div>
        <form method="post">
            <div class="row">
                <div class="col-md-4">
                    <button type="button" id="newCatBtn">New Category</button>
                </div>
            </div>
        </form>
    </div>*@

@*<div>
        <table class="table table-striped">
            <thead class="thead-default">
                <tr>
                    <td>Category Name</td>
                    <td>Actions</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var category in Model)
                {
                    <tr>
                        <td>@category.Name</td>
                        <td>
                            <button class="editCatBtn" data-id="@category.ID">Edit</button>
                            <button class="deleteCatBtn" data-id="@category.ID">Delete</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>*@
<!--#endregion-->

<script>

    $(".pageButtons").click(function () {
        $.ajax({
            url: '@Url.Action("CategoryTable", "Category")',
            data: {
                pageNo: $(this).attr("data-pageNo"),
                search: '@Model.SearchTerm' //Sending search data as well cz otherwise clicking the button will loose search value.
                }
            })
            .done(function (response) {
                $("#tableCategoryContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });

    $("#searchBtn").click(function () {
        var searchValue = $("#searchTxt").val();
        $.ajax({
            url: '@Url.Action("CategoryTable", "Category")', //Using URL helper instead of the hard coded URL which we used before.
                /*'/Category/CategoryTable',*/
            data: {
                search: searchValue
            }
        })
            .done(function (response) {
                $("#tableCategoryContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });

    $("#resetCatBtn").click(function () {
        focusAction("tableCategoryContainer");
        var searchValue = "";

        $.ajax({
            url: '@Url.Action("CategoryTable", "Category")', //Using URL helper instead of the hard coded URL which we used before.
                /*'/Category/CategoryTable',*/
            data: {
                search: searchValue
            }
        })
            .done(function (response) {
                $("#tableCategoryContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });

    $(".deleteCatBtn").click(function () {
        focusAction("tableCategoryContainer");
        $.ajax({
            url: '/Category/Delete',
            data: {
                ID: $(this).attr('data-id')
            }
        })
            .done(function (response) {

                $("#createCategoryContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $(".editCatBtn").click(function () {
        focusAction("createCategoryContainer");
        $.ajax({
            url: '/Category/Edit',
            data: {
                ID: $(this).attr('data-id')
            }
        })
            .done(function (response) {
                $("#createCategoryContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#newCatBtn").click(function () {
        $.ajax({
            url: '/Category/Create',
        })
            .done(function (response) {
                $("#createCategoryContainer").html(response);

                focusAction("createCategoryContainer");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            });
    });
</script>

ClothingBazaar.web/Views/Category/Create.cshtml
@{
    ViewBag.Title = "Create";
    var imageURL = "/Content/images/system/placeholder-image.png";
}

<h2>Create Category</h2>

<form id="catCreateForm">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label><span style="color: red">*</span>Name</label>
                <input class="form-control" name="Name" />
            </div>
            <div class="form-group">
                <label>Description</label>
                <input class="form-control" name="Description" />
            </div>
            <div class="form-group">
                <label>Image</label>
                <input type="hidden" id="ImageURL" name="ImageURL" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
            </div>
            <div class="form-group">
                <div class="comment-respond">
                    <input type="checkbox" name="isFeatured" id="isFeatured" style="display: inline;" value="true">
                    <label for="isFeatured">Featured Category</label>
                </div>
            </div>
            <br />
            <img id="imageContainer" />

        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" id="categoryImage" src="@imageURL" />
            </div>
        </div>
    </div>

    <button id="catSubmit" type="button" class="btn btn-primary">Save</button>
    <button id="catCancel" type="button" class="btn btn-primary">Cancel</button>
</form>

<!--#region Old Code  -->
@*<form id="catCreateForm">

        <div class="form-group">
            <label>Name</label>
            <input class="form-control" name="Name" />
        </div>

        <br />

        <div class="form-group">
            <label>Description</label>
            <input class="form-control" name="Description" />
        </div>
        <br />

        <div class="form-group">
            <label>Image</label>
            <input id="ImageURL" name="ImageURL" type="hidden" />
            <input class="form-control" id="imageUpload" name="Image" type="file" />
        </div>
        <br />

        <div class="comment-respond">
            <input type="checkbox" name="isFeatured" id="isFeatured" style="display: inline;" value="true">
            <label for="isFeatured">Featured Category</label>
        </div>
        <br />

        <img id="imageContainer" />

        <br />

        <button type="button" class="btn btn-primary" id="catSubmit">Save</button> We need to mention the type button here for ajax to pick this button up. also remove any post method
    </form>*@
<!--#endregion-->

<script>
    //Setting up form validation using jQuery
    $("#catCreateForm").validate({
        rules: {
            Name: {
                required: true,
                minlength: 3,
                maxlength: 50
            },
            Description: {
                maxlength: 500
            }
        },
        messages: {
            Name: {
                required: "Name is required",
                minlength: jQuery.validator.format("At least {0} characters required!"),
                maxlength: jQuery.validator.format("At least {0} characters required!")
            },
            Description: {
                maxlength: jQuery.validator.format("Maximum {0} characters are allowed!")
            }
        }
    });

    $("#catSubmit").click(function () {
        if ($("#catCreateForm").valid()) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("Create", "Category")', //'/Category/Create',
                data: $("#catCreateForm").serialize(), //Picks all the values in the text boxes.

            })
                .done(function (response) {
                    focusAction("tableCategoryContainer");
                    $("#tableCategoryContainer").html(response);
                    $("#createCategoryContainer").html("");
                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    Swal.fire({
                        icon: 'error',
                        title: 'Warning',
                        text: 'Please enter all required fields',
                    })
                });
        }
        else {
            Swal.fire({
                icon: 'error',
                title: 'JS Warning',
                text: 'Please enter all required fields',
            })
        }
    });

    $("#catCancel").click(function () {
        focusAction("tableCategoryContainer");
        $("#createCategoryContainer").html("");
    });

    $("#imageUpload").change(function () {
        
        var formData = new FormData();

        var element = this;
        var totalfiles = element.files.length;

        for (var i = 0; i < totalfiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")', //'/Shared/UploadImage',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
            .done(function (response) {
                alert(response);
                if (response.success) {
                    $("#ImageURL").val(response.ImageUrl);
                    $("#categoryImage").attr("src", response.ImageUrl);
                }
                console.log(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            })
    })
</script>

<style>
    .error {
        color: red;
    }
</style>

ClothingBazaar.web/Views/Category/Delete.cshtml
@model ClothingBazaar.Entities.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Are you sure you want to delete the following category?</h2>

<form id="deleteCategoryForm">

    <div class="form-group">

        <input type="hidden" name="ID" value="@Model.ID" />

        <div class="form-group">
            <label>Name</label>
            <input class="form-control" name="Name" value="@Model.Name" readonly />
        </div>
        <br />

        <div class="form-group">
            <label>Description</label>
            <input class="form-control" name="Description" value="@Model.Description" readonly />
        </div>
        <br />

        <button type="button" id="deleteCategory" class="btn btn-primary">Confirm Delete</button>
        <button type="button" id="cancelBtn" class="btn btn-primary">Cancel</button>
    </div>
</form>

<script>
    $("#deleteCategory").click(function () {
        $.ajax({
            type: "POST",
            url: '@Url.Action("Delete", "Category")',//'/Category/Delete',
            data: $("#deleteCategoryForm").serialize() //Picks all the values in the text boxes.
        })
            .done(function (response) {
                $("#tableCategoryContainer").html(response);
                $("#createCategoryContainer").html("");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#cancelBtn").click(function () {
        $.ajax({
            url: '@Url.Action("CategoryTable", "Category")',//'/Category/CategoryTable'
        })
            .done(function () {
                $("#createCategoryContainer").html("");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });
</script>

ClothingBazaar.web/Views/Category/Edit.cshtml
@model EditCategoryViewModel

@{
    ViewBag.Title = "Edit";

    var isFeaturedCheck = Model.isFeatured ? "checked" : string.Empty;

    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/images/system/placeholder-image.png";

}

<h2>Edit Category</h2>

<!--#region Old Code  -->
@*<form id="catEditForm">
        <div class="form-group">
            <input type="hidden" name="ID" value="@Model.ID" />

            <div class="form-group">
                <label>Name</label>
                <input class="form-control" name="Name" value="@Model.Name" />
            </div>
            <br />

            <div class="form-group">
                To submit a button, set it up in a form tag
                <label>Description</label>
                <input class="form-control" name="Description" value="@Model.Description" />
            </div>

            <div class="comment-respond">
                <input type="checkbox"
                       name="isFeatured"
                       id="isFeaturedEdit"
                       @isFeaturedCheck
                       style="display: inline;"
                       value="true">
                <label for="isFeatured">Featured Category</label>
            </div>
            <br />

            <br />
            <div class="form-group">
                <label>Edit Image</label>
                <input id="EditImageURL" name="ImageURL" type="hidden" />
                <input id="editImageUpload" class="form-control" name="Image" type="file" />
            </div>
            <br />

            <label>Current Image Selected</label>
            <br />
            <div id="ImageCategoryCaption"></div>
            <img id="EditImageContainer">

            <br />

            <button type="button" class="btn btn-primary" id="editCatBtn">Save</button>
            <button type="button" class="btn btn-secondary" id="cancelEditCatBtn">Cancel</button>
        </div>
    </form>*@
<!--#endregion-->

<form id="catEditForm">
    <input type="hidden" name="ID" value="@Model.ID" />

    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" name="Name" value="@Model.Name" />
            </div>
            <div class="form-group">
                <label>Description</label>
                <input class="form-control" name="Description" value="@Model.Description" />
            </div>
            <div class="form-group">
                <label>Image</label>
                <input type="hidden" id="EditImageURL" name="ImageURL" value="@Model.ImageURL" />
                <input class="form-control" id="editImageUpload" name="ImageURL" type="file" />
            </div>
            <div class="form-group">
                <div class="comment-respond">
                    <input type="checkbox"
                           name="isFeatured"
                           id="isFeaturedEdit"
                           @isFeaturedCheck
                           style="display: inline;"
                           value="true">
                    <label for="isFeatured">Featured Category</label>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img src="@imageURL" class="img-thumbnail img-fluid" id="EditImageContainer" />
            </div>
        </div>
    </div>
    <button id="editCatBtn" type="button" class="btn btn-primary">Update</button>
    <button type="button" class="btn btn-secondary" id="cancelEditCatBtn">Cancel</button>
</form>

<script>

    $("#cancelEditCatBtn").click(function () {
        focusAction("tableCategoryContainer");
        $("#createCategoryContainer").html("");
    });

    $("#editCatBtn").click(function () {
        $.ajax({
            type: "POST",
            url: '@Url.Action("Edit","Category")',//'/Category/Edit',
            data: $("#catEditForm").serialize() //Picks all the values in the text boxes.
        })
            .done(function (response) {
                focusAction("tableCategoryContainer");
                $("#tableCategoryContainer").html(response);
                $("#createCategoryContainer").html("");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#editImageUpload").change(function () {
        var formData = new FormData();

        var element = this;
        var totalfiles = element.files.length;

        for (var i = 0; i < totalfiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")',//'/Shared/UploadImage',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
            .done(function (response) {
                if (response.success) {
                    $("#EditImageURL").val(response.ImageUrl);
                    //This 'ImageUrl' should have the same name as in Shared Controller
                    $("#EditImageContainer").attr("src", response.ImageUrl);
                    //$("#ImageCategoryCaption").remove();
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            })
    })

</script>

ClothingBazaar.web/Views/Category/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/jquery.validate.min.js"></script>

<!--#region Old Code  -->
@*<div class="container">
        <div id="tableCategoryContainer">
            @{
                Html.RenderAction("CategoryTable");
            }
        </div>

        <hr />

        <div id="createCategoryContainer">

        </div>
    </div>*@
<!--#endregion Old Code  -->

<section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section">
                    <h2 class="title">
                        Categories
                    </h2>
                </div>
            </div>
        </div>
        <div id="tableCategoryContainer">
            @{
                Html.RenderAction("CategoryTable");
            }
        </div>

        <hr />
        <div id="createCategoryContainer">

        </div>
    </div>
</section>

<script>
    function focusAction(controlToFocus) {
        $('html, body').animate({
            scrollTop: $("#" + controlToFocus).offset().top - 100
        }, 1000);
    }
</script>